/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PejabatView.java
 *
 * Created on Aug 5, 2010, 6:15:32 AM
 */
package view;

import entity.Pejabat;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import model.DaoPejabat;
import model.TabelModelPejabat;

/**
 *
 * @author suryono
 */
public class PejabatView extends javax.swing.JFrame {
    //membuat object dari DaoPejabat untuk koneksi ke database
    DaoPejabat dao = new DaoPejabat();
    Pejabat pj;
//   TabelModelPejabat tmp ;
//
//    public TabelModelPejabat getTmp() {
//        return tmp;
//    }



    /** Creates new form PejabatView */
    public PejabatView() {
        try {

            initComponents();
            dao.connect();
            List<Pejabat> list = new ArrayList<Pejabat>();
            list = dao.read();
            TableModel tableModel = new TabelModelPejabat(list);
            tabelPejabat.setModel(tableModel);

        } catch (SQLException ex) {
            Logger.getLogger(PejabatView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNo = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPejabat = new javax.swing.JTable();
        btnInsert = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("No Pejabat");

        jLabel2.setText("Nama Pejabat : ");

        tabelPejabat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "No ", "Nama"
            }
        ));
        tabelPejabat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPejabatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPejabat);

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(84, 84, 84)
                .addComponent(txtNo, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addGap(260, 260, 260))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(51, 51, 51)
                .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addGap(216, 216, 216))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnInsert, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(btnCari, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(txtCari, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1))
                    .addComponent(txtNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2))
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInsert)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate)
                    .addComponent(btnCari)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        try {
            pj = new Pejabat();
            //mendapatkan no dan nama dari view
            pj.setNo(Integer.parseInt(txtNo.getText()));
            pj.setJeneng(txtNama.getText());
            dao.connect();
            dao.insert(pj);
            List<Pejabat> list = new ArrayList<Pejabat>();
            //membaca datanya ke list
            list = dao.read();
            //menampilkan data ke tabel
            TableModel tableModel = new TabelModelPejabat(list);
            tabelPejabat.setModel(tableModel);
            dao.disconnect();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "no tidak boleh sama ");
        }

    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            int noBaris = tabelPejabat.getSelectedRow();
            //jika baris tidak di klik
            if (noBaris < 0) {
                return;
            }

            if (JOptionPane.showConfirmDialog(this, "Yakin menghapus data", "Peringatan", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.CANCEL_OPTION) {
                return ;
            }
            //mendapatkan nilai no dari tabel yang di klik
            Object index = tabelPejabat.getValueAt(noBaris, 0);
            dao.connect();
            dao.delete(Integer.parseInt(String.valueOf(index)));
            List<Pejabat> list = new ArrayList<Pejabat>();
            list = dao.read();
            //menampilkan data ke tabel
            TableModel tableModel = new TabelModelPejabat(list);
            tabelPejabat.setModel(tableModel);
            dao.disconnect();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Kesalahan : " + ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            int baris = tabelPejabat.getSelectedRow();
            Object indek = tabelPejabat.getValueAt(baris, 0);
            int nilaiIndek = Integer.parseInt(String.valueOf(indek));
            dao.connect();
            pj = new Pejabat();
            pj.setNo(Integer.parseInt(txtNo.getText()));
            pj.setJeneng(txtNama.getText());
            pj.setNo(nilaiIndek);
            
            dao.update(Integer.parseInt(txtNo.getText()), pj);
            List<Pejabat> list = new ArrayList<Pejabat>();
            list = dao.read();
            TableModel tableModel = new TabelModelPejabat(list);
            tabelPejabat.setModel(tableModel);
            dao.disconnect();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Kesalahan : " + ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        try {
            //mendapatkan nilai dari yang dicari
            int cari = Integer.parseInt(txtCari.getText());
            List<Pejabat> list = new ArrayList<Pejabat>();
            list = new ArrayList<Pejabat>();
            dao.connect();
            list = dao.read(cari);
            //menampilkan yang dicari
            TableModel tableModel = new TabelModelPejabat(list);
            tabelPejabat.setModel(tableModel);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Kesalahan : " + ex);
        }
    }//GEN-LAST:event_btnCariActionPerformed
    //mengisikan data dari tabel ke textno dan textnama
    private void tabelPejabatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPejabatMouseClicked
        int selected = tabelPejabat.getSelectedRow();
        if (selected < 0) {
            JOptionPane.showMessageDialog(this, "Klik row tabel");
        } else {
            Object noBaris = tabelPejabat.getValueAt(selected, 0);
            txtNo.setText(noBaris.toString());
            txtNama.setText((String) tabelPejabat.getValueAt(selected, 1));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelPejabatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PejabatView().setVisible(true);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTable tabelPejabat;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNo;
    // End of variables declaration//GEN-END:variables
}
